create database storevalue;
use storevalue;
create table storevaluetable(tname varchar(100),tdate varchar(100),tnumberofseats varchar(100),tlocation varchar(100),tdestination varchar(100),tpayment varchar(100));
drop table storevaluetable;
create table storevaluetable(tname varchar(100),tdate varchar(100),tnumberofseats varchar(100),location varchar(100),destination varchar(100),tpayment varchar(100));
desc storevaluetable;
select * from storevaluetable;
create table busdetails(busnumber varchar(10),location varchar(100),destination varchar(100));
desc busdetails;
insert into busdetails values("A00234","coimbatore","chennai");
insert into busdetails values("A00235","coimbatore","madurai");
insert into busdetails values("A00236","coimbatore","theni");
insert into busdetails values("A00237","coimbatore","salem");
insert into busdetails values("A00238","coimbatore","erode");
insert into busdetails values("A00239","coimbatore","namakkal");
insert into busdetails values("A00240","chennai","coimbatore");
insert into busdetails values("A00241","chennai","madurai");
insert into busdetails values("A00242","chennai","theni");
insert into busdetails values("A00243","chennai","salem");
insert into busdetails values("A00244","chennai","erode");
insert into busdetails values("A00245","chennai","namakkal");
insert into busdetails values("A00246","madurai","coimbatore");
insert into busdetails values("A00247","madurai","chennai");
insert into busdetails values("A00248","madurai","theni");
insert into busdetails values("A00249","madurai","salem");
insert into busdetails values("A00250","madurai","erode");
insert into busdetails values("A00251","madurai","namakkal");
insert into busdetails values("A00252","theni","coimbatore");
insert into busdetails values("A00253","theni","chennai");
insert into busdetails values("A00254","theni","madurai");
insert into busdetails values("A00255","theni","salem");
insert into busdetails values("A00256","theni","erode");
insert into busdetails values("A00257","theni","namakkal");
insert into busdetails values("A00258","salem","coimbatore");
insert into busdetails values("A00259","salem","chennai");
insert into busdetails values("A00260","salem","madurai");
insert into busdetails values("A00261","salem","theni");
insert into busdetails values("A00262","salem","erode");
insert into busdetails values("A00263","salem","namakkal");
insert into busdetails values("A00264","erode","coimbatore");
insert into busdetails values("A00265","erode","chennai");
insert into busdetails values("A00266","erode","madurai");
insert into busdetails values("A00267","erode","theni");
insert into busdetails values("A00268","erode","salem");
insert into busdetails values("A00269","erode","namakkal");
insert into busdetails values("A00270","namakkal","coimbatore");
insert into busdetails values("A00271","namakkal","chennai");
insert into busdetails values("A00272","namakkal","madurai");
insert into busdetails values("A00273","namakkal","theni");
insert into busdetails values("A00274","namakkal","salem");
insert into busdetails values("A00275","namakkal","erode");
select * from busdetails;